resources:
- repo: self

trigger:
- main

stages:
  - stage: RunTests
    displayName: Run Tests on All Environments
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
    - job: RunAllTests
      displayName: 'Run Tests in Parallel'
      strategy:
        matrix:
          uat:
            ENV_NAME: 'uat'
            TEST_SCRIPT: 'test:uat'
            # BASE_URL: 'http://t2.silversurfer.ignitiongroup.co.za/Auth'
            ARTIFACT_NAME: 'playwright-report-uat'
          # prod:
          #   ENV_NAME: 'PROD'
          #   TEST_SCRIPT: 'test:prod'
          #   BASE_URL: 'https://silversurfer.ignitiongroup.co.za/Auth'
          #   ARTIFACT_NAME: 'playwright-report-prod'
        maxParallel: 2
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'
        displayName: 'Install Node.js'

      - script: |
          set -ex
          npm install
          npx playwright install
          npx playwright install-deps
        displayName: 'Install dependencies'
        workingDirectory: '$(Build.SourcesDirectory)'

      - script: |
          set -ex
          echo "Running tests for $(ENV_NAME) environment"
          # echo "Using base URL: $(BASE_URL)"
          npm run $(TEST_SCRIPT) -- --config=Playwright.config.js --reporter=html
        displayName: 'Run $(ENV_NAME) Tests'
        workingDirectory: '$(Build.SourcesDirectory)'
        # env:
        #   PLAYWRIGHT_BASE_URL: $(BASE_URL)

      - publish: $(Build.SourcesDirectory)/playwright-report
        artifact: $(ARTIFACT_NAME)
        condition: always()